# Image URL to use all building/pushing image targets
VERSION ?= v0.1.0
DOCKER_REPO := ghcr.io/sergealexandre
BUILDX_CACHE=/tmp/docker_cache

BUILD_TS ?= $(shell date -u +%Y%m%d.%H%M%S)

# To authenticate for pushing in github repo:
# echo $GITHUB_TOKEN | docker login ghcr.io -u $USER_NAME --password-stdin

# You can switch between simple (faster) docker build or multiplatform one.
# For multiplatform build on a fresh system, do 'make docker-set-multiplatform-builder'
#DOCKER_BUILD := docker buildx build --builder multiplatform --cache-to type=local,dest=$(BUILDX_CACHE),mode=max --cache-from type=local,src=$(BUILDX_CACHE) --platform linux/amd64,linux/arm64
DOCKER_BUILD := docker build

# Comment this to just build locally
DOCKER_PUSH := --push


.PHONY: help
help: ## Display this help.
	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m<target>\033[0m\n"} /^[a-zA-Z_0-9-]+:.*?##/ { printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2 } /^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) } ' $(MAKEFILE_LIST)


version: ## Regenerate version and build TS
	@echo "// Generated by Makefile\n\npackage config\n\nvar Version = \"$(VERSION)\"\nvar BuildTs = \"$(BUILD_TS)\"\n" >internal/config/version_.go

# ------------------------------ Docker

.PHONY: docker
docker: version ## Build and push image
	$(DOCKER_BUILD) ${DOCKER_PUSH} -t $(DOCKER_REPO)/mockweb:$(VERSION) -f Dockerfile .

